### ISSUE TITLE
Firmware 8.6 - How to update the switch safely?

### ISSUE THREAD

**Issue by hurda** [fenderle/esphome-vorke-hd41#2]
Hello!

This is not a question about the project itself but how to get the hardware to meet the requirements of using it as you recommended:
How did you manage to update the switch to firmware-version 8.6?

Tons of reviews on Amazon and reports on several forums say that using the firmware-updater offered on Vorke's website leaves the switch bricked.
Apparently the firmware-files from Vorke can't be used with a common ST-Link programmer, which only leaves taking a gamble with the RS232-stuff.

What combination of hardware (RS232-adapter or -port) and software (OS, flashing program, firmware, order of flashing them) were you using to successfully update the switch?

Thank you for your time.

**Comment by fenderle** [comment]
Yes, using the updater from the Website will most certainly brick your device. I bricked my first HD41 by trying that, ordered a new one and with that the serial update worked (probably just pure luck). I then extracted the firmware using an ST-Link and flashed it back to the bricked one - so both of them were working in the end. 

And also yes, you cannot flash the firmware from the website using an ST-Link - it has to be somehow converted or extracted by the update routine.

So unfortunately I would advice against updating the switch since the outcome is mostly up to luck.
